### PR TITLE
Elements overriding

### PR DESCRIPTION
**Pull request by yesmeck**
This PR addresses many long living issues.

Added `components` to allow overriding default table elements.

```javascript
const components = {
  table: MyTable,
  header: {
    wrapper: HeaderWrapper,
    row: HeaderRow,
    cell: HeaderCell,
  },
  body: {
    wrapper: BodyWrapper,
    row: BodyRow,
    cell: BodyCell,
  },
};

<Table components={components} columns={columns data={data}}  />
```

Added `onRow`, `onHeaderRow`, `column[onCell]` and `column[onHeaderCell]` to allow overriding row and cell props.

## Integrate with react-dnd

See https://yesmeck.github.io/table/examples/react-dnd.html

Close https://github.com/ant-design/ant-design/issues/4639, #83

## Integrate with styled-components 

See https://yesmeck.github.io/table/examples/styled-components.html.

## Ability to add any event listener to the table element with `onRow` and `onCell`

Don't need add tons of `onRowXXX`  props.

```javascript
const onRow = (record) => ({
  onClick() { alert(`Clicked ${record.name}`) },
});
<Table columns={columns} data={data} onRow={onRow} />
```

Close https://github.com/ant-design/ant-design/issues/7096, #127, #141, #117, #149

## Ability to optimize table row with sCU

```javascript
class OptimizedRow extends React.Component {
  shouldComponentUpdate(nextProps) {
    // Perform a custom check
  }

  render() {
    return (
      <tr {...this.props } />
    )
  }
}

<Table components={{ body: { row: OptimizedRow } }} />
```

Related https://github.com/ant-design/ant-design/issues/2884

## Others

Close https://github.com/ant-design/ant-design/issues/5776, #139

### CODE REVIEW

**Comment by afc163** [comment]
#137

**Comment by yesmeck** [comment]
Yeah, aligned cell can be implemented through custom component:

```javascript
const CenterCell = (props) => <th  {...props} style={{ textAlign: 'center' }} />;

<Table components={{ body: { cell: CenterCell } }} />
```

**Comment by afc163** [comment]
column.align will be easier to use.

**Comment by yesmeck** [comment]
After introducing `onRow` and `column[onCell]`, we can deprecate `onRowClick`, `onRowDoubleClick`, `onRowMouseEnter`, `onRowMouseLeave`, `onRowContextMenu`, `column[onCellClick]`.

**Comment by yesmeck** [comment]
`getBodyWrapper` can be deprecated as well.

**Comment by liuyangc3** [comment]
> Ability to add any event listener to the table element with `onRow` and `onCell`
Don't need add tons of onRowXXX props.

补充一下 `onCell` 是在 columns 里, 看上面的例子 还以为是写在 `Table` 上
```
const columns = { 
  onCell: record => ({
  onClick() { alert(`Clicked ${record.name}`) },
});
<Table columns={columns} data={data} onRow={onRow} />
```

**Comment by Clee681** [comment]
@yesmeck Is there a way to just wrap the `body.row` element without having to manually re-create it?

**Comment by ashirbad29** [comment]
do components work in virtual table ? I have been trying to add a custom row component but it seems it is getting ignored when virtual table is enabled.

**Pull request merged**
