### PR TITLE
add onHeaderClick on column properties

### PR DESCRIPTION
**Pull request by ds3783**
In out product document, product manager require a feature that is: when user click table header, system popup a modal dialog which explain that specific column is how generated. 
Thus, I think we need a event listener function pass to the "th" element.

### CODE REVIEW

**Comment by yesmeck** [comment]
Try using `column[title]`:

```javascript
const columns = [
    { title: <span onClick={handleTittleClick}>Name</span> }
];
```

**Comment by ds3783** [comment]
the clickable area did cover padding of "th" !

**Comment by henryzp** [comment]
@ds3783 ， it can use now?

**Comment by henryzp** [comment]
Does this onHeadClick not need to provide parameters?

Because in my needs inside, I was hoping to click thead to be able to sort。I need to know some information, such as the current thead。

I see your code，but it cannot help me

**Comment by yesmeck** [comment]
https://github.com/react-component/table/pull/171

**Pull request closed without merging**
