### PR TITLE
feat: Fixed Summary columns

### PR DESCRIPTION
**Pull request by zombieJ**
Follow up of #503

close #503
close ant-design/ant-design#25116
ref ant-design/ant-design#23170
ref ant-design/ant-design#5710
ref ant-design/ant-design#14795

### 👁 Preview

* https://table-git-fix-summary-react-component.vercel.app/demo/fixed-columns
* https://table-git-fix-summary-react-component.vercel.app/demo/sticky-header-and-summary

### CODE REVIEW

**Comment by hemengke1997** [comment]
yo，终于更新了啊！ 牛逼牛逼

**Comment by flyingCrp** [comment]
Nice work

**Comment by hemengke1997** [comment]
@zombieJ  老哥，codesanbox打开示例报错，我更新了pro-table，用在项目中，也是报一样的错误

image

**Comment by pierre-b** [comment]
Thanks for the merge guys!!

**Comment by flyingCrp** [comment]
need upgrade document

**Comment by hemengke1997** [comment]
> need upgrade document

https://table-git-fix-summary-react-component.vercel.app/demo/sticky-header-and-summary

**Comment by flyingCrp** [comment]
> > need upgrade document
> 
> https://table-git-fix-summary-react-component.vercel.app/demo/sticky-header-and-summary

it's not work . im sure i got the `  "antd": "^4.16.0",`
my code like this :
```

const TableSummary = ({columns, data, isSelect}) => {
    if (!Object.keys(data).length) return null;
    return (
        <Summary fixed >
            <Summary.Row>
                {isSelect && <Summary.Cell key={'selected-clm'} />}
                {columns.map((clm, idx) => {
                    if (idx === 0) {
                        return (
                            <Summary.Cell key={clm.dataIndex}>合</Summary.Cell>
                        );
                    }
                    if (!clm.children || !clm.children.length) {
                        return (
                            <Summary.Cell key={clm.dataIndex} align={clm.align}>
                                <ParseClm clm={clm} data={data} />
                            </Summary.Cell>
                        );
                    } else {
                        return clm.children.map((row) => {
                            return (
                                <Summary.Cell
                                    key={row.dataIndex}
                                    align={row.align}
                                >
                                    <ParseClm clm={row} data={data} />
                                </Summary.Cell>
                            );
                        });
                    }
                })}
            </Summary.Row>
        </Summary>
    );
};
export default TableSummary;


```

**Comment by hemengke1997** [comment]
> > > need upgrade document
> > 
> > 
> > https://table-git-fix-summary-react-component.vercel.app/demo/sticky-header-and-summary
> 
> it's not work . im sure i got the ` "antd": "^4.16.0",`
> my code like this :
> 
> ```
> 
> const TableSummary = ({columns, data, isSelect}) => {
>     if (!Object.keys(data).length) return null;
>     return (
>         <Summary fixed >
>             <Summary.Row>
>                 {isSelect && <Summary.Cell key={'selected-clm'} />}
>                 {columns.map((clm, idx) => {
>                     if (idx === 0) {
>                         return (
>                             <Summary.Cell key={clm.dataIndex}>合</Summary.Cell>
>                         );
>                     }
>                     if (!clm.children || !clm.children.length) {
>                         return (
>                             <Summary.Cell key={clm.dataIndex} align={clm.align}>
>                                 <ParseClm clm={clm} data={data} />
>                             </Summary.Cell>
>                         );
>                     } else {
>                         return clm.children.map((row) => {
>                             return (
>                                 <Summary.Cell
>                                     key={row.dataIndex}
>                                     align={row.align}
>                                 >
>                                     <ParseClm clm={row} data={data} />
>                                 </Summary.Cell>
>                             );
>                         });
>                     }
>                 })}
>             </Summary.Row>
>         </Summary>
>     );
> };
> export default TableSummary;
> ```

what's wrong? 

I used the nearly code and there is no error

**Comment by flyingCrp** [comment]
> > > > need upgrade document
> > > 
> > > 
> > > https://table-git-fix-summary-react-component.vercel.app/demo/sticky-header-and-summary
> > 
> > 
> > it's not work . im sure i got the ` "antd": "^4.16.0",`
> > my code like this :
> > ```
> > 
> > const TableSummary = ({columns, data, isSelect}) => {
> >     if (!Object.keys(data).length) return null;
> >     return (
> >         <Summary fixed >
> >             <Summary.Row>
> >                 {isSelect && <Summary.Cell key={'selected-clm'} />}
> >                 {columns.map((clm, idx) => {
> >                     if (idx === 0) {
> >                         return (
> >                             <Summary.Cell key={clm.dataIndex}>合</Summary.Cell>
> >                         );
> >                     }
> >                     if (!clm.children || !clm.children.length) {
> >                         return (
> >                             <Summary.Cell key={clm.dataIndex} align={clm.align}>
> >                                 <ParseClm clm={clm} data={data} />
> >                             </Summary.Cell>
> >                         );
> >                     } else {
> >                         return clm.children.map((row) => {
> >                             return (
> >                                 <Summary.Cell
> >                                     key={row.dataIndex}
> >                                     align={row.align}
> >                                 >
> >                                     <ParseClm clm={row} data={data} />
> >                                 </Summary.Cell>
> >                             );
> >                         });
> >                     }
> >                 })}
> >             </Summary.Row>
> >         </Summary>
> >     );
> > };
> > export default TableSummary;
> > ```
> 
> what's wrong?
> 
> I used the nearly code and there is no error

yeah, ther is no error ,but .the summary row  is also not stickied 
so i dont know how to config it to showlike this merge

**Comment by hemengke1997** [comment]
> yeah, ther is no error ,but .the summary row is also not stickied
> so i dont know how to config it to showlike this merge

allright, me too. maybe there is something we missed

**Comment by hemengke1997** [comment]
动画5

@flyingCrp  this is workable

**Comment by flyingCrp** [comment]
> 动画5
> 
> @flyingCrp this is workable

wow, is my code wrong? 
let me  see your code ,thanks

**Comment by hemengke1997** [comment]
> wow, is my code wrong?
> let me see your code ,thanks

just like the example
```
summary={() => (
  <Table.Summary fixed={true}>
    <Table.Summary.Row>
      <Table.Summary.Cell index={0} />
      <Table.Summary.Cell index={1} colSpan={2}>
        Summary
      </Table.Summary.Cell>
      <Table.Summary.Cell index={3} colSpan={8}>
        Content
      </Table.Summary.Cell>
      <Table.Summary.Cell index={11} colSpan={2}>
        Right
      </Table.Summary.Cell>
    </Table.Summary.Row>
  </Table.Summary>
)}
```

**Comment by hemengke1997** [comment]
> wow, is my code wrong?
> let me see your code ,thanks

maybe u should restart ur server after upgrade antd

**Comment by yujajoe** [comment]
有办法把summary放到tbody上面固定吗

**Comment by miristein** [comment]
I had the same problem - adding **index** to each cell was the solution.

`() => (<Table.Summary fixed={true}>
                <Table.Summary.Row>
                    <Table.Summary.Cell index={0}>
                        <Typography.Text strong={true}>First pilot column</Typography.Text>
                    </Table.Summary.Cell>
                    <Table.Summary.Cell index={1}>
                        Content
                    </Table.Summary.Cell>
                    <Table.Summary.Cell index={2}>
                        Content
                    </Table.Summary.Cell>
                </Table.Summary.Row>
                <Table.Summary.Row>
                    <Table.Summary.Cell index={0}>
                        <Typography.Text strong={true}>Second pilot column</Typography.Text>
                    </Table.Summary.Cell>
                    <Table.Summary.Cell index={1}>
                        Content
                    </Table.Summary.Cell>
                    <Table.Summary.Cell index={2}>
                        Content
                    </Table.Summary.Cell>
                </Table.Summary.Row>
            </Table.Summary>)`

**Pull request merged**
