### PR TITLE
Set mouse cursor to pointer when row is clickable

### PR DESCRIPTION
**Pull request by purplecones**
If a row is clickable it should indicate it to the user. This PR makes the cursor turn into a hand when user hovers over a table row that can be clicked. This shows the user that something will happen when the row is clicked.

### CODE REVIEW

**Comment by purplecones** [comment]
Any feedback on this? Would you consider merging?

**Comment by purplecones** [comment]
@afc163 any feedback? Would you merge this?

**Comment by afc163** [comment]
I am not sure about this, I think it should use `rowClassName` to customize the styles of the rows.

**Comment by yesmeck** [comment]
`rowClassName` is better solution.

**Pull request closed without merging**
