### PR TITLE
add rowStyle and expandedRowStyle Properties

### PR DESCRIPTION
**Pull request by jun0205**
I added rowStyle and expandedRowStyle Properties on table row.
add examples/style.html

### CODE REVIEW

**Comment by paranoidjk** [comment]
What's your use case? 

I think this makes it too complicated, i think you can use `rowClassName + css` to do custom style staff.

**Comment by jun0205** [comment]
Tr style attribute.

**Comment by waiwaiku** [comment]
I'm really looking forward to adding these properties like expandedRowStyle、rowStyle...
It will help me to add CSS animations.

**Comment by waiwaiku** [comment]
@paranoidjk  
可不可合并下，通过设置rowStyle属性，可以不让{display: 'none'}设置不被写死，
这样就可以添加CSS动画了，来达到展开收起缓冲效果。

**Comment by yesmeck** [comment]
https://github.com/react-component/table/pull/171

**Pull request closed without merging**
