### PR TITLE
Define expandIconColumnIndex =-1 to remove expandicon,use  rowclick t…

### PR DESCRIPTION
**Pull request by yuyangvi**
…o expand instead.

When we need row click to expand a new row without a icon, we should define expandIconColumnIndex =-1

### CODE REVIEW

**Comment by yuyangvi** [comment]
当expandIconColumnIndex =-1 时，使用行点击替代来点击展开图标的事件

**Comment by yuyangvi** [comment]
当expandIconColumnIndex =-1 时，使用行点击替代来点击展开图标的事件

**Comment by afc163** [comment]
Maybe a `expandRowByClick` is easier to understand.

```
<Table
  columns={columns}
  data={data}
  expandedRowRender={record => <p>{record.a}</p>}
  expandRowByClick     // do not show expand icon when expandRowByClick is true
/>
```

**Comment by yuyangvi** [comment]
OK, expandRowByClick is added

**Comment by afc163** [comment]
1. Make `expandIconAsCell` and `expandRowByClick` indepent.
2. Don't bubble click event when click the expand icon

https://github.com/react-component/table/commit/c053f6d882d1ef220ea612063b27aab7ee8c36fe

**Comment by afc163** [comment]
4.5.0

Example: http://react-component.github.io/table/examples/expandedRowRender.html

**Comment by wonyun** [comment]
how nice to support the feature that the expanded icon can be removed

**Pull request merged**
