### PR TITLE
Remove Header Scroll in Y-direction

### PR DESCRIPTION
**Pull request by mohamed-seada-1994**

### CODE REVIEW

**Comment by afc163** [comment]
Removing extra scrollbar will cause that column don't align correctly

Trace https://github.com/ant-design/ant-design/issues/4637

**Comment by afc163** [comment]
We will try to resolve by https://github.com/ant-design/ant-design/pull/10796 's way

**Comment by mohamed-seada-1994** [comment]
That's not fully true as you mention.
The columns don't align correctly for scroll-y example when we remove the scroll.
But they don't align correctly by default in scroll-xy example.
I think the actual problem is with the fixed column width not in scroll
I have a question, why using seperate table for header instead of using thead?

**Comment by yoyo837** [comment]
@mohamed-seada-1994 For fixed table header.

**Comment by mohamed-seada-1994** [comment]
@yoyo837 see this http://maxdesign.com.au/jobs/sample-fixed-thead/index.htm

**Comment by yoyo837** [comment]
I think I understand what you means now.🙂

**Pull request closed without merging**
