### PR TITLE
feat: add headerAlign and bodyAlign

### PR DESCRIPTION
**Pull request by marswong**
@benjycui refer to ant-design/ant-design#2465, and #137 can be closed.

### CODE REVIEW

**Comment by afc163** [comment]
```jsx
columns={[{
  'align': 'left',
}]}
```

This will be better.

**Comment by marswong** [comment]
I thought about this, seperated config is flexible, but uncommon in daily usage.
Such as the statistic data always need a table with unified center-aligned table head and right-aligned table body.
So it may be better to expose a unified config API, and if really needed, users can just set `text-align` in the column render function, but it's really unusal.

**Comment by afc163** [comment]
It is a common usage for sepecify align for one column: https://ant.design/components/table/#components-table-demo-bordered

**Comment by marswong** [comment]
Got it.

**Pull request closed without merging**
